# Generated by Django 3.0.5 on 2020-09-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('movieId', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
